spring:
  cloud:
    gateway:
      routes:
        server:
          webflux:
            routes:
              - id: r1
                uri: http://localhost:8058
                predicates:
                  - Path=/customers/**
              - id: r2
                uri: http://localhost:8057
                predicates:
                  - Path=/accounts/**